autoSectionPath = "src"
changelog = false
gitSourceBranch = "main"
title = "GreenTeaUtilities"

[docusaurus]
tagline = "Utilities for the GreenTea library."

# [[navbar.items]]

[home]
enabled = true
includeReadme = false

[[home.features]]
title = "Missing Types"
description = "GreenTea's missing types are included here."

[[home.features]]
title = "Additional Types"
description = "Additions such as Set and specific EnumItems are included."

[footer]
copyright = "Copyright © 2024 Bura Games. Made with Moonwave."
