autoSectionPath = "src"
changelog = false
gitSourceBranch = "main"
title = "GreenTeaUtilities"

[docusaurus]
baseUrl = "/greentea-utilities"
tagline = "Utilities for the GreenTea library."

# [[navbar.items]]

[home]
enabled = true
includeReadme = false

[[home.features]]
description = "GreenTea's missing types are included here."
title = "Missing Types"

[[home.features]]
description = "Additions such as Set and specific EnumItems are included."
title = "Additional Types"

[footer]
copyright = "Copyright © 2024 Bura Games. Made with Moonwave."
