[package]
authors = ["HowManySmall <howmanysmall@gmail.com>", "Corecii <>", "Osyris <>"]
description = "Additional utilities for the GreenTea library."
exclude = ["**"]
include = ["src", "src/**", "wally.toml", "wally.lock", "default.project.json", "LICENSE"]
license = "MIT"
name = "howmanysmall/greentea-utilities"
realm = "shared"
registry = "https://github.com/UpliftGames/wally-index"
version = "1.6.0"

[dependencies]
Debug = "howmanysmall/debug@1.0.1"
GreenTea = "corecii/greentea@0.4.10"

[dev-dependencies]
